version: '2'
services:
  rabbitmq:
    image: kurt/rabbitmq:stomp
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
  splunk:
    image: kurt/splunk:stomp
    environment: 
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
    hostname: splunk
    ports:
      - 8000:8000
      - 8089:8089
    volumes:
       - ./apps/splunk-tcs-secure-app:/opt/splunk/etc/apps/splunk-tcs-secure
    depends_on:
       - rabbitmq
  
